language: ruby
rvm:
- 2.1.1
bundler_args: "--without kitchen_vagrant"
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script:
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: LfiY968ZLs/FkL1b5ImkN72v60kw58GwT2q2oMCz9uoHRETprpne80CXU1EPW/vi4NrfMCBfr5R77hhU+KqIBmx5hu2RTsaviUNda6O1qLG3mMwjc38L5jlOS3kiIGWlHfs9Qm2lURoul/A3HIWtD572JTPy0YF7+RaYU0zupfc=
  - secure: ZfjqJh/j+/RhHk9ceDSzF12cR8JhBzzLUdNX5szZPWFxeIsCCFN+uGn1PET8Hzl3QWuTyON0rBWC+CV6iBfOfFMxMM5NLkhSeLt5gtlVTK6uzRoT3c1YfPj1PtSvUuJyxgjsjc/0OeU+Vro0p4hWTmI3iOxwzTqkd0aTwmmdMd8=
  - secure: Iz8VI/GwItzx9Z57qf7wg23gGqTUOhsYLPXDElLlYDQ99CPU6YDOkyB/WKjy9pDL0TRor8u0yAQkWVhzG9iEHHOrI/fX3u4U4B/+wO5OOL26Ex4wh0NGZ3l+DDLRjaxlJQceagHoMcQ3bY4h5ykOqS8DA3H3MehSeS1UrznGfx8=
  - secure: UvEr2I8OU3I2Eho9GznEp9IbOVazWxZiVRfSXZE3yTFMZupdJm7kl1tRBFySmzT0h3FIOtGlQz2dz7afLbJqvPUTN8U7brnDIUSUM+48IPf8l5dAXaBa6yMz4MJFz1ZiOR5EN5e13qnGLr53tcGP1YkicFPX2tj3TpfYGVqTCe4=
  - secure: ChJCia+sSnu3AJUX8UIOe2deZlHw5/ENmm5dbM8lSiymKkjZfPI82EmvbK+C7Yn8HSIUXqG7IpygQGC5gwsABKm+DFowjxPf6qMJFuOVSMy0iBNK1tEeGMvWgQUCDCmMDzt2/t/F+kkwMwITh2eqD33h4NeXhBSMagBlUitV128=
  - secure: Jy4xhXgdtXEixh3pnnSNkF26YcNWUvN5OVSzAxCQxtg63rCYKdDkt46/DqUcdIb9Rc6lB2xTX/MUvFRSWg741Ib4K/0GcICp+tNY8YfDA46x6p1RhSAJV4stguinY75JFmR7gozL6+vrxQKqvr5bul+5K8ADtJ8VB5BRTDV/lYc=
  - secure: FehuyE5Pb/sXNITGxQTYYW1Giuos+uhVgUhyzjoSdd+V3TPI5chfTiBHL7dJOp2u5pKN2papb3fchCroUk5L57/tYuyH2V593zPvIgrbzxpoEfn2zVc92/23Ci3+YVzoeRS6XnOJHMk3FFSCY8DAjVGkJhD/ja2XtSyCLZnAVjc=
  - secure: aeY00k4g64jPNWpTAMCb7JFdZpt5LtWqhwH5wmLmCOk/KtmouIVAyVI+bkD7xPx4SrIkSI7xcq8ArnFZz6z1rPxhyDCnNzaSN7NR8t579Rv1lcIfDNyLTc3EHTB9nLMvv4d26FT7oHrB1hLHOYJTE5vVO9lH06Q5+dCwEmjBJuA=
  - secure: Eft01hEu1Rc72bfgihvIky5e72WAq4hDsqpQpDgKICxcw5pVE0od1GD3J5v5bEgqZ09FVP8/27Vu3dE1FEay0awXz2i6zwmgRgFSeOrfQZ457ut21oJYryPWBK3iMz77H430/U1L/Gbx1/pAnkc0hWd8dBKBhSNAOGK8SlKbs0w=
  - secure: EQ24cZtLiYOeVJlF9MSqJYoWp7qlDmx/I9xS67q4/pNjWZh8c27U61c97fjS+dOY6oJBtD3XfpJaonSYTB/brhUq/xWkWbB7AUu/0okxZGDEY6HkfKniyfcSZlbScn86cRfhX6VZkCV2/oA7b3mYxPfi6KYNhci4TRG8bp/ToTA=
  - secure: LjDEL69wMaPlDZpWbajJHV/7zjVtmaxqlgRJBcIyjKHTjKugxphsAtFOBEDmRKm22GTUNCk6VgmQSBFAw9LTQRY0UziOKPfl6nZvA5MS5Qgn9C3yj0d+xpuT9lhOM7IVZmzM2GdI4oIHsEzlEHNiR6katiQijQE5hDFxVk7evQw=
  - secure: ZF1CV0GYm1U7gI/vx7nORPhZ3GGfZagvyAOCuKLUUfc3aq2IPZGn7ADhkgLPc+TskbvBg1oUXaiYceFfZdA3ElORYu2VZ4iPOZ4HYOGzoxQ+0jDSHNIR6sZ9TMPTJw5Ty0yGpNRk9mcA+toyKsYOFliC0iSl2a9H1fU6NtT4tt0=
  - secure: RriylmmKISP8vQMKxOG8QDNJOYgUJDIrsF8uOnUeQcr/oYbLXQ3F0sKwQKP8QDaZB6r1DzewLKE3Il5cEyiqJvvqqOU0d8uPxhA+94ucId7p9t9Hvb9sWlFMbO/6crWre8Vdr+uyz9arJkTGh+AA8bGudhALSll8kgktKiO1nGQ=
  - secure: Ju+yc0025342iU885buJAZJaL9U/an0tAUxT/DgiUuOivS9bqEeltil++HozlxZRRX9uNg54NPdD72BQaEC23pWeK179UAJDUggyr3hbFGTuJtAmeiGDr32ft6tYkJuDgN9E1xfG9c/fIJGOti5b5vpZ+55T+sSh+iV24gcUE8w=
  - secure: SoaXe0LnIHSjbIL60xFuqQ2yzebvWwofWQUI+z6SmJtXhwlBUrfvJ8xjfdB+C/DcIrWaEr6M7IHrb6dEQxnvrW6Bdhv9Vfis2zPuAJHQJl+ym+gJUQneJIN1KeltlsDa9o7UaVWMPdGkzoIyo3C2wGMUcLZFCHXizsSG0KzowJo=
  - secure: fTHiKs8iPwK82qISGCFSgpBgOPl160X8swVzzCQ91nridrWR6VgI7+XLnHtS10Zf92YWumhFNIwOQ/b7XALE2VtYs8LoQrNj7sP4XAxL2fky86hJFKBuhg5vtRELJ7a5liXIVZb1U57mATeFPyPXqsm+FCJFBbdnfYGek6CiRLU=
  - secure: EQSWR2w/4MPhzinzzyLXX4utDAGLpHin6bX8BQa7WCEFGgKe8Sx/wUNjtoK9V8vNJK13c/8JNQBvPEm7RWPo49yKG8xJ3UhdfhgNKqTltoGEsx9mY+gpoYud8dbQmGJ+nLp8eCGOWZ+AB9c4ojj+UR+2PPEYZd7azqUcT0mL8Es=
  - secure: NmU/EMYBNwFhqITV0uFO/UP3LieHT4M++JyASSyYRCtsf9r/yhjzrFOl545WOsNgjNO3hnJ44OyRU84b4GshfybrxbLt/7mUNK/HZfBSlMNhafsx9Tv4sz8y3ZPg4iKcOOgV+V2Cex0G1vIgWMzazld9q26hWzThgRFeeINYYL8=
  - secure: KNlE3Rew81p3QTL14Qb1UWKM19fOhEDxH9sWnxri5DqOeqRSOzxqjNHmtI/u/ZFVSGzZtT4/hSdqgqXTJ41vncPIlgIbZju2U+RTHrQleLcXHcoTri/S7cAqOnNB6iof+9FIUaodCquRPxHRKMTFsgHC2DbIqEysS98vpMMBkZg=
  - secure: CV88GiMbkZ7jfH3SSScG8KQHRJyg7Xgrsqj0r/YPrnmHK0SfBgV9BKmMdxxTJ3BOrCLEj0mEWFhBb6zXYRHx3AG5BxaCzWIfJpNAdDuYrCdEm9lEQukILmAthaMpp5KOes04BvsK4IMrpkdAbf4ulv1JNj5gFr+lyjHGQb0nXCE=
  - secure: bdTdST0xDrSRN6NJqs+35iIQ1ZkmKs00boOrhiIcfnJkSWR9p0aimX2A6PYmm4khFSrKJFr+6O2YurHHfUxF/BOz8VedDmbjWJJ/MvTAQ9OvH2n+WL0VvICcYXg5RMin0Eo8hNm+5pOkXLrK+LwKEca+7o2Z+Ygmii9u5yIIfkU=
  - secure: VceT5PniewXlGT5e9bx6dHVfy7oGCFjr554NyJzxLYKpycB840qif7NQRLeiLpkBJ+SytjXk3GwK1/psEnO8YkWSu1lHHBYRHRTvDNQ4P/WSwDS9/p7XhPMMb1F3Xpy150f032EG+Qi/l1AMkyGxpYquiYC/OCjLqJULj9ZxIzQ=
  - secure: cZusStpN+NAGnwn90CMTuCy7aYOuONkx1NEbUxnS9Tu+EBtsgV9gHHmQ9233zYyCzQxUvN6/fnERXUGdeExHETdKVJ4Vv3Ca2gZiNxmE1aTIAhPU0hlGwriv9r5YPJYb2UsOYr9I1pd2dEEacQbsglwQbPo1HGa2yk34viVggPc=
  - secure: LxJ81g0XIjjAFpFjdlXSI6dCCIMIhInjDHrwxB+WjWMx6Hi+1ySd+i0ksBdOxSSsWxaUsvJfj3z8uK2tUia4EE9r+/P4/hbVRHoZLiPnwqfdRgaHFmtBMkAcqFoClYUsXmvtnTVax1l1hBlcq0SVNAE8cBThnnQegYBLvkaQu/I=
  - secure: OZUqdZPOZQ+O7V4k6E3842l1B1zRtN5MkqWnEKhV29hEPC+3u0uPiPtelsAIIVFxfibD2fzBECEQsbJxha8Rls+jMgW2AXyxpxNv2Acw/jOGezxXrJorHJnmrttKNPRdFwbLl7MOO2wMuPlv8rDwFmRKlf5qLLCJ1lpO9UAENOU=
  - secure: asBWgBxWJaABaExQqGqpfaJV51wwotaN8Cxn0eWOvhLyg8XWxzAzDZnuJxNHrFYYoQ7N+XHWELf8gOIP7nRpUy0qv3PjZD/SluuxPmuqZcGMuEufEvQYEYOpkqoj1QXCuQCdxOsf2SryxQIjwxPkorDkKh/pcUol7o2pmTtUMeI=
  - secure: CF9nvPUbO++VnNaXBYY+Oh/3581QrPUHQeoslnOriBH/5ZboNdzyNKnnNOHooHnDEkNLLz4NsY7gnRS06jzgPQ3O6d7p81DL5fIVaPmLHck4wrFmgPDhq+u7ucf3b0NCAQc/c38wafcIWkzzPrduzaFNiMeKwSPWt3L0ZXyGVNM=
  - secure: cc0guwTpw46rT0um27zezVrYZBd3yAX1ncpm8tcxlXR7FnqslQtKPzxg0sbk6MPqTIu73hq43TF1vpb9qSbatxV1K5Yku6/zdZ1VJ4s2z4CbxgssPqJxUrnFis8du0D64WwxycpG1RMb/Q827wdUwMhacYTfZTnFVjRAKugLCto=
  - secure: YEO3bLXSdcBniHDga3l5jwfXChkmA1I1qGyJybBPKsedhlb/7P/GQOgdWtSi7bEnBLOpGkz6hNCZ8Z1kTHydDwlgAPZUi+FfV8GmvcjprtcEahdBLEYCdFEbyydE/Mtf57t6FznlD958zQbd832rteXZ2fYBIHayeQOOdH9vnt4=
  - secure: exhd/6/BXjcIZA9zCBpyBT+0j5H0eHY7f2JquWw7H/Y/5kq4mLOZvNsskkfifu11Xh9oq/yiz0/xezRYJm9AdqvDHav6R+IxB5SlFhbSqZxR7Nygc3JZSHU68R79eb7BR/6XaZUG24Sku+hs9DV7Uu6aS+KkoOGBz4dePDlfHUk=
  - secure: DzhtwmJJkzYOb1DcjyrpH2rC4yt4n3pLd2VQjXT/eKysJ4BkV76TLonJVYr0GOKheZnetO5nt79iQ6D2LujFhfEqMvi+MW9ZhiaT4QF7IrzpOCFtJeapKmh1NJFpdEnh98wJWEBtpNfVWtGAHfEkrhQaf/6dvtb4G0R5969FrVQ=
  - secure: etdJ4pR7oKpPlXIZdG8ByWZo02Dh59VVEHz086nx8V0O/osPK4dgM4yf4T0hMxaQTRVbfnVlDhpdnK6CJPfLW0zkB8+hz7dAo2ioPdBZpFa3t6w/vt0vn4j/APfxRCN68g4KsuG/S+CHOfCmSsksZ0QUUJi9DvUm+TgyV9R/IaE=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
